### ISSUE TITLE
Ex1

### ISSUE THREAD

**Issue by anarut** [FiodarKarnilovich/educational_project#2]
```
    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>
```
везде 11 а в parent 1.7 - мб стоит оставить в только в parent и с 17 java

```
    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>
```

----

https://github.com/FiodarKarnilovich/educational_project/blob/97788bdc1956d5d6a412936495afe27ab5e9dbe8/pom.xml#L37
я полагаю что этого будет достаточно только в web.xml cейчас

**Comment by FiodarKarnilovich** [comment]
@anarut исправил
